siteName: Escap'Orium
productionUrl: https://www.escaporium.eu/
languages:
  - code: fr
    status: published
    keepUrlPrefix: true
  - code: en
    status: published
    keepUrlPrefix: true
collections:
  - organizations
  - events
  - creativeWorks
  - people
newTabLinkTypes:
  - external
metadata:
  image: ""
