siteName: Escap'Orium
productionUrl: https://escap-orium.github.io/poko-website-builder/
languages:
  - code: fr
    status: published
    keepUrlPrefix: true
  - code: en
    status: published
    keepUrlPrefix: true
collections:
  - organizations
  - events
  - creativeWorks
  - people
newTabLinkTypes:
  - external
metadata:
  image: ''
